### ISSUE TITLE
Handling spaces in term searches

### ISSUE THREAD

**Issue by emilepetrone** [Yelp/yelp-api#105]
I'm getting 400s when I try to pass a term with a space. "Golf course" as an example returns a 400.

`python sample.py --location="San Francisco, CA" --term="golf course"`

I've also tried "golf+course", still getting 400s. Are spaces not allowed in a term search?

Specifically I'm using the code from the Python V2 sample.

**Comment by mittonk** [comment]
Hm, that example works fine for me.  Spaces are definitely allowed
1. Do terms without spaces like "burgers" work as expected?  Want to make sure spaces are actually the problem.
2. Is your repo up-to-date?  `git log` should show commits from February and January 2016 --- if you don't see anything since November, you may have a stale Python example.  (In particular, I'm wondering if you're hitting fixed bug #22 ).

**Comment by emilepetrone** [comment]
@mittonk figured it out. It was hitting the search limit. My bad, closing

**Comment by mittonk** [comment]
Wonderful, sounds good!
