### ISSUE TITLE
php sample mishandles unicode characters in business ids

### ISSUE THREAD

**Issue by butterfield** [Yelp/yelp-api#118]
When hitting the biz endpoint with a business id that has a special character in it (like ó), the sample does not encode the id properly in the url, resulting in a 400 response.

Sample output:

3 businesses found, querying business info for the top result "la-fusión-san-francisco-2"

PHP Fatal error:  Curl failed with error #400: {"error": {"text": "Signature was invalid", "id": "INVALID_SIGNATURE", "description": "Invalid signature. Expected signature base string: GET\u0026https%3A%2F%2Fapi.yelp.com%2Fv2%2Fbusiness%2Fla-fusi%25C3%25B3n-san-francisco-2\u0026oauth_consumer_key%3DSjxGRtHjlhJ-LgJ6LOU1Ug%26oauth_nonce%3D3f7a515e4ae33a6fb4e360f617d0f970%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1457552415%26oauth_token%3DOy0ePIdCw7mqX6fJmVyKOPEZLwSRnBKs%26oauth_version%3D1.0"}} in /nail/home/jeffreyb/pg/yelp-main/sample_php.php on line 81

**Comment by woohooyayaya** [comment]
I think I know why.

This is the signed url in percent encoding:
https%3A%2F%2Fapi.yelp.com%2Fv2%2Fbusiness%2Fla-fusi%C3%B3n-san-francisco-2%3Foauth_consumer_key%3DtC6J9T0YPuJNcGV2kMv_1A%26oauth_nonce%3Dad1189bc4d948bad3e7ef0b2c99c99c5%26oauth_signature%3DA1mZEw8l%252Bpxi8MjQ3lL1FGh9eYc%253D%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1457824978%26oauth_token%3Dv3Co_EwQ6D99ruSBU6LWGieJFkaBB2HI%26oauth_version%3D1.0

This is the expected base string:
GET\u0026https%3A%2F%2Fapi.yelp.com%2Fv2%2Fbusiness%2Fla-fusi%25C3%25B3n-san-francisco-2\u0026oauth_consumer_key%3DtC6J9T0YPuJNcGV2kMv_1A%26oauth_nonce%3Dad1189bc4d948bad3e7ef0b2c99c99c5%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1457824978%26oauth_token%3Dv3Co_EwQ6D99ruSBU6LWGieJFkaBB2HI%26oauth_version%3D1.0

So ó gets interpretted as %C3%B3 , and in the base string because of percent encoding it interprets the % as %25, causing the result to be %25C3%25B3.

Any idea of fixes?

**Comment by daveymuso** [comment]
I am getting this too... so surely every one is... we need a fix

**Comment by mittonk** [comment]
Yep, this breaks the PHP sample pretty thoroughly in many parts of the world.

**Comment by mittonk** [comment]
Reproduced error, debugging.

**Comment by mittonk** [comment]
@butterfield , @woohooyayaya , @daveymuso : Fixed.  Please pull master to get the new code!

**Comment by woohooyayaya** [comment]
Thanks.
