### ISSUE TITLE
YLPBusiness property attribute request

### ISSUE THREAD

**Issue by WadeSellers** [Yelp/yelp-api#144]
Hi Yelp! 

May I please request an added read-only property on the YLPBusiness class? An immutable id string would allow the ability for a developer to connect their database item to a specific YLPBusiness object. Since the YLPBusiness.identifier property is mutable, a change to the .identifier property creates issues when tying to an outside databases item that wants to correlate with a specific YLPBusiness object.

An immutable id string on the YLPBusiness class would add a strong connection to your YLPBusiness objects that we could use to correlate data against.

**Comment by watterso** [comment]
Hi @WadeSellers,
Looking into the header file [YLPBusiness.h](https://github.com/Yelp/yelp-ios/blob/caff9f887b0710a8f65b40534d40ff068b7ef97c/Classes/Response/YLPBusiness.h#L43) we see that `YLPBusiness.identifier` and all fields are `readonly` or immutable. So after a YLPBusiness is constructed based off a response on our servers, it cannot be changed.

I think what you really are trying to get at is [based off of our previous discussion](https://github.com/Yelp/yelp-ios/pull/36#issuecomment-228274189), when a business is moved or renovated it gets a new biz_id. The reason we consider moved or renovated business to be a new business is because substantial changes affect the experience customers have at business so old reviews, hours, photos don't apply. 

The way we handle it in the backend, and how I suggest you should too, is by maintaining a database table that tracks these moves something like:

|source_id | destination_id|
| ----------- | ----------------- |
|zum-schwan-frankfurt-am-main | zum-schwan-frankfurt-am-main-2|

Then if you ever get a `YLPBusiness` that has `closed == YES` you should do a search request with some of the `YLPBusiness`'s  info to find if its been moved/renovated and if it has, add a row to the table like I did above. Finally whenever you are going to use a biz_id to request something you should check to see if it is a `source_id` in the above table and change the request to actually to the query with the corresponding `destination_id`.

**Comment by WadeSellers** [comment]
@watterso ... That's perfect! You explained it spot on. Thank you so much for taking the time. That's an excellent strategy and that's exactly what I'll do.

**Comment by watterso** [comment]
Awesome, happy do help :D
