### ISSUE TITLE
how to make  searchable for yelp API 

### ISSUE THREAD

**Issue by srikanthjanjirala1** [Yelp/yelp-api#197]
hi,
yelp api work very  well but how can i searchable them? 
my code is

<?php
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.yelp.com/v3/businesses/search?categories=restaurants&limit=10&sort_by=distance&offset=5&location=49 Geary St, San Francisco, CA 94108&price=1,2&radius=800&open_at=11",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_HTTPHEADER => array(
    "Authorization: Bearer <access token>"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  $obj = json_decode($response,true);
  

  echo "<pre>";
  print_r($obj );
}

please reply me 
                                                                                                                      thank you

**Comment by virgytam** [comment]
@sriknthjanjirala1 - this repo is for Public API V2, but this is a V3/Fusion issue. Can you close this and re-raise the issue in https://github.com/Yelp/yelp-fusion

**Comment by virgytam** [comment]
hi @sriknthjanjirala1, this repo is actually for Public API V2 but your issue is with v3/Fusion. For Fusion related issues, please use the https://github.com/Yelp/yelp-fusion repo. 

For this particular issue, I'm not quite understanding the question. Are you unable to view the query results? What does your search response look like? The response should look like the response here: https://www.yelp.com/developers/documentation/v3/business_search

**Comment by dan98765** [comment]
We are in the process of archiving this API v2 github repository, and as part of that are closing out all issues. 

---
Announcement:
As of June 30, 2018, the API v2 has been discontinued and v2 endpoints no longer work. It has been replaced by [Yelp's Fusion API](https://www.yelp.com/fusion). This github repository is archived. There is a new Yelp Fusion-specific github repository at https://github.com/Yelp/yelp-fusion.
