### ISSUE TITLE
Objective-C OAuth library does not use ARC

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-api#57]
@MatthewHendy writes in #32 :
>In my build settings the 'Objective-C Automatic Reference Counting' flag is set to yes, yet I have 94 errors relating to 'release' , 'autorelease' , ARC restrictions, and ARC casting rules. I copied this code into my project and double checked my ARC flag and it doesn't run. If I turn off ARC then it runs fine.

First step: Repro and find a few of these 94 errors.

@MatthewHendy: Do you have 2-3 example errors we could look at?

**Comment by mittonk** [comment]
@SSheldon , feel like taking a first pass?

**Comment by SSheldon** [comment]
@MatthewHendy, sorry for the trouble! This issue is because the OAuth library used in our Objective-C code sample does not use ARC. It should work if you add the `-fno-objc-arc` compiler flag to the OAuth files (like in these steps: http://stackoverflow.com/a/6658549).

On a related note, if you have any ARC-compatible OAuth libraries to recommend, I'd be happy to hear it :)

**Comment by MatthewHendy** [comment]
That seemed to work SSheldon, thank you!
