### ISSUE TITLE
Add R example?

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-api#86]
We might want to do an example in R.

The tricky bit is OAuth:
* http://stackoverflow.com/questions/3391460/oauth-access-for-r

The simplest approach is probably an OAuth library in R:
* https://cran.r-project.org/web/packages/ROAuth/index.html has recent edits, which is a good sign.

**Comment by today-is-a-good-day** [comment]
Yes, please! I'm struggling a lot with that and can't get past the oauth procedure. 

The writer of this thread here suggests to use httr instead of ROAuth (apparently he has contacted the author of the ROAuth package who advised him to do so):
http://stackoverflow.com/questions/27728318/using-the-yelp-api-with-r-attempting-to-search-business-types-using-geo-coordin

I've tried out the approach but I get an "INVALID SIGNATURE" error. One of the httr-functions he uses (sign_oauth1) seems to be deprecated, don't know if that's causing the problem...

Anyways, an example for the OAuth in R would be AWESOME! 

Keep it up :)

**Comment by mittonk** [comment]
@today-is-a-good-day : Thanks for the pointer on httr, and good luck!

**Comment by mittonk** [comment]
@today-is-a-good-day : Added R example, have a look!
